import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import { Poppins } from "next/font/google";
import { CartProvider } from "@/context/CartContext";
import { SpeedInsights } from "@vercel/speed-insights/next";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});
export const metadata = {
  title: "Berry Ecommerce Shop",
  icons: {
    icon: "/loaderImage.png",
  },
  description: "Generated by MD MAHEDI ZAMAN",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <CartProvider>
          <Header className="h-screen" />
          {children}
          <Footer />
        </CartProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
